### PR TITLE
uuid.NewV4() does not need uuid.Must anymore

### LINKED ISSUE #27: .\config.go:27:23: not enough arguments in call to uuid.Must
Im really sorry if this is the wrong place to be posting this. And im really sorry for how useless I am at these sorts of things!

Im using Git to build TyphoonLimbo with the commands listed on the Wiki.
When i do go build I get this error:

$ go build
# TyphoonLimbo
.\config.go:27:23: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)

### PR DESCRIPTION
**Pull request by mikroskeem**
Fixes #27

### CODE REVIEW

**Comment by mikroskeem** [comment]
Travis build fails because of outdated dependencies, I ensured that mine are on latest versions.

**Comment by skyforce77** [comment]
Can you fix the travis issue ? I think that simply removing any "go get" in .travis.yml and add "go install" instead could fix it.

I don't have any computer for a week, so I can't try on my own, sorry

**Comment by mikroskeem** [comment]
I kinda don't want to touch Travis as it hates me probably more than it does you. :smile: 

_Well, maybe just not today_

**Comment by skyforce77** [comment]
Ok (It hates me too xD). I'll merge this when I'll have a computer

**Comment by skyforce77** [comment]
Is it fixed now ?
https://github.com/TyphoonMC/TyphoonLimbo/commit/43b3c6f01246de982c4284ae776fb2f8293f2244

**Comment by mikroskeem** [comment]
Seems like so

**Pull request closed without merging**
